[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "always"

[environments]
  [environments.production]
    PORT = "3000"
    NODE_ENV = "production"
    FRONTEND_URL = "${RAILWAY_PUBLIC_DOMAIN}"
    
  [environments.development]
    PORT = "3000"
    NODE_ENV = "development"